### ISSUE TITLE
Build fails on several errors

### ISSUE THREAD

**Issue by h1z1** [RPM-Outpost/discord#3]
Not sure if this was meant for Fedora only(?) but there are a few problems.  

- wget --show-progress is not a standard option or a build dep is needed on a newer wget

```
$ wget --help |grep progress
       --progress=TYPE           select progress gauge type.
```

- Discord appears to have changed their URL / removed the tar.gz  option (503 error).  
```

- sourced files like common-function.sh and terminal-colors.sh are not +x

This strangely covers up other cwd assumptions throughout the script.

Kinda weird they don't offer rpms.. then again it's largely a secret operation overall lol (app calls home.. a lot).

**Comment by TheElectronWill** [comment]
Hello !

- I developed my script with Fedora in mind, that's why it was not tested with other distributions. What do you use ?
- Could you give a more precise error ? I've tested these two adresses and it worked:
  - https://discordapp.com/api/download?platform=linux&format=tar.gz
  - https://discordapp.com/api/download/canary?platform=linux&format=tar.gz 
- Sourced files do not need to have the executable bit.
